module Main (main) where

import Control.Exception (bracket)
import Data.ByteString.Char8 qualified as ByteString
import Data.List.NonEmpty (NonEmpty (..))
import Data.Set qualified as Set
import Data.Text qualified as Text
import Database.PostgreSQL.LibPQ qualified as PQ
import Database.PostgreSQL.Migrate
  ( MigrationPlan,
    VerificationReport (..),
    defaultRunOptions,
    migrationComponent,
    migrationPlan,
    runMigrationPlan,
    sqlMigration,
    verifyMigrationPlan,
  )
import Hasql.Connection.Settings qualified as Settings
import Keiro.Migrations (keiroMigrations)
import Kiroku.Store.Migrations (kirokuMigrations)
import System.Environment (getArgs, getEnv)
import System.Exit (die)
import Text.Read (readMaybe)

main :: IO ()
main = do
  plan <- either (die . show) pure composedPlan
  settings <- connectionSettings
  getArgs >>= \case
    ["up"] -> do
      result <- runMigrationPlan defaultRunOptions settings plan
      either (die . show) (const (putStrLn "migration plan applied")) result
    ["verify"] -> do
      verifyLedger settings plan
      verifyLiveSchema
    ["verify-ledger"] -> verifyLedger settings plan
    ["verify-live"] -> verifyLiveSchema
    _ -> die "usage: hinagata-keiro-migrate up|verify|verify-ledger|verify-live"

verifyLedger :: Settings.Settings -> MigrationPlan -> IO ()
verifyLedger settings plan = do
  result <- verifyMigrationPlan defaultRunOptions settings plan
  case result of
    Left failure -> die (show failure)
    Right VerificationReport {issues = [], pendingMigrations = []} -> putStrLn "migration ledger verified"
    Right report -> die ("migration ledger differs from the complete plan: " ++ show report)

verifyLiveSchema :: IO ()
verifyLiveSchema =
  bracket (PQ.connectdb "") PQ.finish $ \connection -> do
    status <- PQ.status connection
    if status /= PQ.ConnectionOk
      then die "live schema verification could not connect"
      else do
        let statement =
              ByteString.unlines
                [ "SELECT to_regclass('public.keiro_reference_data') IS NOT NULL",
                  "  AND (SELECT is_identity = 'YES' FROM information_schema.columns",
                  "       WHERE table_schema = 'public' AND table_name = 'keiro_reference_data' AND column_name = 'id')",
                  "  AND has_table_privilege('hinagata_example_app', 'public.keiro_reference_data', 'SELECT')",
                  "  AND has_table_privilege('hinagata_example_app', 'public.keiro_reference_data', 'INSERT')"
                ]
        executed <- PQ.exec connection statement
        case executed of
          Nothing -> die "live schema verification returned no result"
          Just result -> do
            resultStatus <- PQ.resultStatus result
            if resultStatus /= PQ.TuplesOk
              then die "live schema verification query failed"
              else do
                value <- PQ.getvalue result (PQ.toRow (0 :: Int)) (PQ.toColumn (0 :: Int))
                if value == Just "t" then putStrLn "application live schema verified" else die "application live schema differs from its declared contract"

composedPlan :: Either String MigrationPlan
composedPlan = do
  kiroku <- either (Left . show) Right kirokuMigrations
  keiro <- either (Left . show) Right keiroMigrations
  applicationMigration <- either (Left . show) Right (sqlMigration "create-reference-data" applicationSql)
  application <- either (Left . show) Right (migrationComponent "hinagata-keiro-example" (Set.singleton "keiro") (applicationMigration :| []))
  either (Left . show) Right (migrationPlan (kiroku :| [keiro, application]))

applicationSql :: ByteString.ByteString
applicationSql =
  ByteString.unlines
    [ "CREATE TABLE public.keiro_reference_data (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code text NOT NULL UNIQUE, label text NOT NULL);",
      "GRANT USAGE ON SCHEMA kiroku, keiro TO hinagata_example_app;",
      "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA kiroku, keiro TO hinagata_example_app;",
      "GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA kiroku, keiro TO hinagata_example_app;",
      "GRANT SELECT, INSERT ON public.keiro_reference_data TO hinagata_example_app;",
      "GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.keiro_reference_data_id_seq TO hinagata_example_app;"
    ]

connectionSettings :: IO Settings.Settings
connectionSettings = do
  host <- Text.pack <$> getEnv "PGHOST"
  portText <- getEnv "PGPORT"
  port <- maybe (die "PGPORT must be a port number") pure (readMaybe portText :: Maybe Word)
  if port == 0 || port > 65535 then die "PGPORT is out of range" else pure ()
  user <- Text.pack <$> getEnv "PGUSER"
  database <- Text.pack <$> getEnv "PGDATABASE"
  pure (Settings.hostAndPort host (fromIntegral port) <> Settings.user user <> Settings.dbname database)
